name: CLT latest release installation tests
run-name: CLT latest release installation tests ${{ github.sha }}

on:
  schedule:
    - cron: '00 20 * * *'

# cancels the previous workflow run when a new one appears in the same branch (e.g. master or a PR's branch)
concurrency:
  group: clt_nightly_${{ github.ref }}
  cancel-in-progress: true

jobs:
  clt_rhel_release_installation:
    uses: manticoresoftware/clt/.github/workflows/clt-template.yml@v2
    with:
      version: v2
      docker_images: |
        [
          {"image": "centos:7"},
          {"image": "almalinux:8"},
          {"image": "almalinux:9"},
          {"image": "oraclelinux:9"},
          {"image": "amazonlinux:latest"}
        ]
      run_args: -e TELEMETRY=0
      test_prefix: test/clt-tests/installation/rhel-release-
  clt_deb_release_installation:
    uses: manticoresoftware/clt/.github/workflows/clt-template.yml@v2
    with:
      version: v2
      docker_images: |
        [
          {"image": "ubuntu:bionic"},
          {"image": "ubuntu:focal"},
          {"image": "ubuntu:jammy"},
          {"image": "debian:buster"},
          {"image": "debian:bullseye"},
          {"image": "debian:bookworm"}
        ]
      test_prefix: test/clt-tests/installation/deb-release-
